[tool.ruff]
# Устанавливаем максимальную длину строки (88 - стандарт для black, но 100 тоже популярно)
line-length = 88

# Включаем основные правила:
# E = pycodestyle (ошибки стиля)
# F = Pyflakes (логические ошибки, как неиспользуемые переменные)
# I = isort (сортировка импортов)
select = ["E", "F", "I"]

# Исключаем папки, которые не нужно проверять
exclude = [
    ".git",
    ".venv", # папка виртуального окружения
    "__pycache__",
]

[tool.ruff.format]
# Эта строчка говорит ruff, что он также должен работать как форматер
# (замена для инструмента "black")
enabled = true
